name: Sync Markdown to victoriadrake.github.io

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout hashnode-blog repo
      uses: actions/checkout@v3
      with:
        repository: victoriadrake/hashnode-blog
        path: hashnode-blog

    - name: Checkout victoriadrake.github.io repo
      uses: actions/checkout@v3
      with:
        repository: victoriadrake/victoriadrake.github.io
        path: victoriadrake.github.io
        token: ${{ secrets.TOKEN }}

    - name: Reformat tags, replace first line with date, rename cover to image, then copy to victoriadrake.github.io
      run: |
        # Get the current date in the format YYYY-MM-DDTHH:MM:SS.sssZ
        current_date=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
        
        for file in $(find hashnode-blog/ -name '*.md'); do
          # Replace the first line with the frontmatter and date
          sed -i "1s/^---$/---\ndate: $current_date/" "$file"
          
          # Reformat tags in the frontmatter, removing commas
          awk '/^tags:/{gsub(/, /, "\n    - "); sub(": ", ":\n    - ")}1' "$file" > temp.md && mv temp.md "$file"
          
          # Rename the 'cover' key to 'image' in the frontmatter
          sed -i 's/^cover:/image:/' "$file"
          
          # Copy the markdown file to the content/posts directory
          cp "$file" "victoriadrake.github.io/content/posts/"
        done

    - name: Commit and push changes to victoriadrake.github.io
      run: |
        cd victoriadrake.github.io
        git config --global user.name "workflow"
        git config --global user.email "ihalp@victoria.dev"
        git add .
        git commit -m "Sync new blog posts from hashnode-blog"
        git push origin master
