name: Sync Markdown to victoriadrake.github.io

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout hashnode-blog repo
      uses: actions/checkout@v3
      with:
        repository: victoriadrake/hashnode-blog
        path: hashnode-blog

    - name: Checkout victoriadrake.github.io repo
      uses: actions/checkout@v3
      with:
        repository: victoriadrake/victoriadrake.github.io
        path: victoriadrake.github.io
        token: ${{ secrets.TOKEN }}

    - name: Reformat tags and add date to markdown files, then copy to victoriadrake.github.io
      run: |
        # Get the current date in the format YYYY-MM-DDTHH:MM:SS.sssZ
        current_date=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
        
        for file in $(find hashnode-blog/ -name '*.md'); do
          # Reformat tags in the frontmatter
          sed -i '/^tags:/s/: \(.*\)/:\n    - \1/' "$file"
          sed -i 's/, /,\n    - /g' "$file"
          
          # Insert the current date after the first '---' line only if a date is not already present
          if ! grep -q "^date:" "$file"; then
            sed -i "/^---/!b;/^---/{n;s/^/date: $current_date\n/}" "$file"
          fi
          
          # Copy the markdown file to the content/posts directory
          cp "$file" "victoriadrake.github.io/content/posts/"
        done

    - name: Commit and push changes to victoriadrake.github.io
      run: |
        cd victoriadrake.github.io
        git config --global user.name "workflow"
        git config --global user.email "ihalp@victoria.dev"
        git add .
        git commit -m "Sync new blog posts from hashnode-blog"
        git push origin master
